version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: db 
    environment:
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_DATABASE: chat_system_production
      MYSQL_USER: yahia
      MYSQL_PASSWORD: yahia
    ports:
      - "3306:3306"
